version: "3.8"
services:
  server:
    volumes:
      - type: bind
        source: ./StudentsApp/StudentsApp/
        target: /source/
    build:
      context: .
      target: final
    ports:
      - 80:80
