version: "3.8"
services:
  server:
    volumes:
      - type: bind
        source: ./StudentsApp/StudentsApp/
        target: /source/
    build:
      context: .
      target: final
    ports:
      - 80:80
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022 
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
