version: "3.8"
services:
  server:
    volumes:
      - type: bind
        source: ./StudentsApp/StudentsApp/
        target: /source/
    build:
      context: .
      target: final
    ports:
      - 80:80
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev-db
    