apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: bb-site
              image: projcs-server
              imagePullPolicy: Never
              ports:
                - containerPort: 80
                  hostPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: projcs-db-1
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb-db: projcs-db-1
   template:
      metadata:
         labels:
            bb-db: projcs-db-1
      spec:
         containers:
         - name: projcs-db-1
           image: projcs-db
           imagePullPolicy: Never
           env:
            - name: MYSQL_DB
              value: dev-db
            - name: MYSQL_ROOT_PASSWORD
              value: root
           ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 80
        targetPort: 80
        nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
   name: projcs-db-1
   namespace: default
spec:
   selector:
      bb-db: projcs-db-1
   ports:
      - protocol: TCP
        port: 3306
        targetPort: 3306